### ISSUE TITLE
Should render 0

### ISSUE THREAD

**Issue by apaleslimghost** [i-like-robots/hyperons#13]
Text children with a value of `0` (the number) aren't rendered [because they're falsy](https://github.com/i-like-robots/hyperons/blob/master/src/child-elements.js#L10). Preact stringifies number children [as soon as they're passed in](https://github.com/developit/preact/blob/18878f4d73a668fb03a1e0dbc808f1f63818c46d/src/h.js#L55).

**Comment by i-like-robots** [comment]
Thanks for reporting, should be an easy fix
